"""Configuration file template generator for setup wizard."""

import logging
import shutil
import yaml
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional

from ..utils.atomic_io import atomic_write_json

logger = logging.getLogger(__name__)


class ConfigGenerator:
    """Generate config files from validated setup data."""

    def __init__(self, workspace: Path):
        self.workspace = workspace
        self.config_dir = workspace / "config"

    def generate_jira_config(self, jira_data: Dict[str, Any]) -> Dict[str, Any]:
        """Generate jira.yaml content."""
        return {
            "server": jira_data["server"],
            "email": jira_data["email"],
            "default_project": jira_data.get("project", "")
        }

    def generate_github_config(self) -> Dict[str, Any]:
        """Generate github.yaml content with sensible defaults."""
        return {
            "default_branch": "main",
            "require_pr_approval": True
        }

    def generate_framework_config(self, repos: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate agent-framework.yaml with minimal settings."""
        return {
            "llm": {
                "mode": "claude_cli",
                "use_mcp": False,  # Disabled by default for MVP
                "default_model": "sonnet"
            },
            "task_processing": {
                "poll_interval": 5,
                "max_retries": 3
            },
            "repositories": [
                {
                    "name": r["name"],
                    "github_repo": r["github_repo"],
                    "jira_project": r["jira_project"]
                }
                for r in repos
            ],
            "workflows": {
                "default": ["architect", "engineer", "qa"]
            }
        }

    def generate_agents_config(self) -> Dict[str, Any]:
        """Generate agents.yaml with sensible defaults."""
        # Load from agents.yaml.example if it exists
        example_path = self.config_dir / "agents.yaml.example"
        if example_path.exists():
            with open(example_path, "r") as f:
                return yaml.safe_load(f)

        # Otherwise create minimal config with core agents
        return {
            "agents": [
                {
                    "id": "engineer",
                    "name": "Software Engineer",
                    "queue": "engineer",
                    "enabled": True,
                    "prompt": "See config/docs/workflow_modes.md for details"
                },
                {
                    "id": "qa",
                    "name": "QA Engineer",
                    "queue": "qa",
                    "enabled": True,
                    "prompt": "See config/docs/workflow_modes.md for details"
                },
                {
                    "id": "architect",
                    "name": "Technical Architect",
                    "queue": "architect",
                    "enabled": True,
                    "prompt": "See config/docs/workflow_modes.md for details"
                }
            ]
        }

    def generate_env_file(self, jira_data: Dict[str, Any], github_data: Dict[str, Any]) -> str:
        """Generate .env file content."""
        return f"""# Agent Framework Environment Variables
# Generated by setup wizard on {datetime.now().isoformat()}

JIRA_SERVER={jira_data["server"]}
JIRA_EMAIL={jira_data["email"]}
JIRA_API_TOKEN={jira_data["api_token"]}
GITHUB_TOKEN={github_data["token"]}
"""

    def write_all_configs(
        self,
        jira_data: Dict[str, Any],
        github_data: Dict[str, Any],
        repos: List[Dict[str, Any]]
    ) -> List[str]:
        """Atomically write all config files.

        Returns:
            List of created file paths

        Raises:
            Exception: If any write operation fails (with rollback)
        """
        created_files = []
        backup_dir: Optional[Path] = None

        try:
            # Create config directory if needed
            self.config_dir.mkdir(parents=True, exist_ok=True)

            # Backup existing configs if any
            if list(self.config_dir.glob("*.yaml")):
                backup_dir = self.workspace / f".config_backup_{int(datetime.now().timestamp())}"
                backup_dir.mkdir(parents=True, exist_ok=True)
                for yaml_file in self.config_dir.glob("*.yaml"):
                    shutil.copy2(yaml_file, backup_dir / yaml_file.name)
                logger.info(f"Backed up existing configs to {backup_dir}")

            # Write jira.yaml
            jira_path = self.config_dir / "jira.yaml"
            with open(jira_path, "w") as f:
                yaml.dump(self.generate_jira_config(jira_data), f, default_flow_style=False)
            created_files.append(str(jira_path))

            # Write github.yaml
            github_path = self.config_dir / "github.yaml"
            with open(github_path, "w") as f:
                yaml.dump(self.generate_github_config(), f, default_flow_style=False)
            created_files.append(str(github_path))

            # Write agent-framework.yaml
            framework_path = self.config_dir / "agent-framework.yaml"
            with open(framework_path, "w") as f:
                yaml.dump(self.generate_framework_config(repos), f, default_flow_style=False)
            created_files.append(str(framework_path))

            # Write agents.yaml
            agents_path = self.config_dir / "agents.yaml"
            with open(agents_path, "w") as f:
                yaml.dump(self.generate_agents_config(), f, default_flow_style=False)
            created_files.append(str(agents_path))

            # Write .env file
            env_path = self.workspace / ".env"
            with open(env_path, "w") as f:
                f.write(self.generate_env_file(jira_data, github_data))
            # Set restrictive permissions
            env_path.chmod(0o600)
            created_files.append(str(env_path))

            # Validate configs can be loaded
            from ..core.config import load_config, load_agents

            _ = load_config(framework_path)
            _ = load_agents(agents_path)

            logger.info(f"Successfully created {len(created_files)} config files")
            return created_files

        except Exception as e:
            logger.error(f"Failed to write configs: {e}")

            # Rollback: delete created files
            for file_path in created_files:
                try:
                    Path(file_path).unlink(missing_ok=True)
                except Exception as cleanup_error:
                    logger.warning(f"Failed to cleanup {file_path}: {cleanup_error}")

            # Restore backup if available
            if backup_dir and backup_dir.exists():
                logger.info("Restoring backup configs...")
                for backup_file in backup_dir.glob("*.yaml"):
                    shutil.copy2(backup_file, self.config_dir / backup_file.name)

            raise Exception(f"Config generation failed: {e}")
